[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]

[window]
decorations = "full"
startup_mode = "{{@@ ALACRITTY_STARTUP_MODE @@}}"
opacity = 1.0
dimensions = { columns = 120, lines = 36 }
padding = { x = 10, y = 10 }

[scrolling]
history = 50000
multiplier = 3

[font]
{%@@ if USE_NERD_FONT == "YES" @@%}
normal = { family = "{{@@ ALACRITTY_FONT @@}}", style = "Medium" }
size = 16.0
{%@@ else @@%}
normal = { family = "{{@@ ALACRITTY_FONT_DEFAULT @@}}", style = "Regular" }
size = 15.0
{%@@ endif @@%}


[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[selection]
save_to_clipboard = true

[[mouse.bindings]]
mouse = "Left"
action = "Copy"

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"
