#!/bin/sh
[ -r /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n
# ===== x setting =====
# xfce4-power-manager --no-dpms # disable dpms
xfconf-query -c xfwm4 -p /general/use_compositing -s false
# ===== clipboard access =====
vncconfig -iconic &
# ===== clean env =====
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
unset GNOME_KEYRING_SOCKET
unset GNOME_DESKTOP_SESSION_ID

# ===== force X11 =====
export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11

# ===== IM (fcitx5) =====
# export XMODIFIERS="@im=fcitx"
# export GTK_IM_MODULE=fcitx
# export QT_IM_MODULE=fcitx
# export XIM="fcitx"
# export USE_XOPENIM="fcitx"
# export DEFAULT_IM_MODULE="fcitx"

# (command -v fcitx5 >/dev/null 2>&1 && fcitx5 -d >/dev/null 2>&1) || true

# ===== merge Xresources =====
[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

if [ -f /etc/os-release ]; then
    . /etc/os-release
    case "$ID" in
        rocky|almalinux)
            case "$VERSION_ID" in
                9*)
                    echo "Detected Rocky/AlmaLinux 9 -> start XFCE"
                    exec dbus-launch --exit-with-session startxfce4
                    ;;
                *)
                    echo "Detected Rocky/AlmaLinux older than 9 -> fallback"
                    exec /etc/X11/xinit/xinitrc
                    ;;
            esac
            ;;
        ubuntu)
            case "$VERSION_ID" in
                24.*)
                    echo "Detected Ubuntu 24 -> start XFCE"
                    exec gnome-session
                    ;;
                *)
                    echo "Detected Ubuntu (not-24) -> fallback"
                    exec /etc/X11/xinit/xinitrc
                    ;;
            esac
            ;;
        *)
            echo "Other distro... fallback"
            if [ -x /etc/X11/xinit/xinitrc ]; then
                exec /etc/X11/xinit/xinitrc
            elif [ -f /etc/X11/xinit/xinitrc ]; then
                exec sh /etc/X11/xinit/xinitrc
            fi
            ;;
    esac
else
    echo "/etc/os-release does not exist"
    # maybe openbox?
    # exec twm
    exec /etc/X11/xinit/xinitrc
fi
