alias   rm="rm -i"
alias   cp="cp -i"
alias   mv="mv -i"
alias   grep="grep --color -In"
alias   vi="vim"
alias   l="ls -AlhF --color=auto"
alias   ll="ls -lhF --color=auto"
alias   llt="ls -lhF --color=auto --time-style=long-iso"
alias   lsd="ls -dlh --color=auto"
alias   dfh="df -Th"
alias   duh="du -h --max-depth=1"
alias   type="type -a"
alias   cd..="cd .."
alias   cd~="cd ~"
alias   cd-="cd -"
alias   ..="cd .."
alias   ...="cd ../.."
alias   ..2="cd ../.."
alias   ..3="cd ../../.."
alias   lsg="ls -lhFa | grep"
#alias  duhome='du -h --max-depth=1 --exclude "./.*"'
alias   freeh="free -h"
alias   psg="ps axuww | grep -v grep | grep"
alias   psgl="ps axlww | grep -v grep | grep"
# alias   ff="find . -type f -name"
# alias   fd="find . -type d -name"
alias   cdw="cd ${HOME}/workspace"
# follow the XDG standards, https://wiki.archlinux.org/title/XDG_user_directories
alias   cdd="cd ${HOME}/Downloads"
alias   q="exit"
alias   grepconf='grep "^[^#]"'
alias   histg="history | grep"
alias   histl="history | less"
alias   path='echo -e ${PATH//:/\\n}'
