export ZSH=$HOME/.oh-my-zsh

HIST_STAMPS="yyyy-mm-dd"
DISABLE_AUTO_UPDATE="true"
ZSH_THEME="example"
ZSH_THEME_TERM_TITLE_IDLE=""
# Note that zsh-syntax-highlighting must be the last plugin sourced.
plugins=(git history z sudo zsh-autosuggestions zsh-completions
        extract safe-paste colored-man-pages history-substring-search
        zsh-syntax-highlighting
        )

source $ZSH/oh-my-zsh.sh

# config zsh-users/zsh-autosuggestions
# ZSH_AUTOSUGGEST_STRATEGY=(history completion)
# ZSH_AUTOSUGGEST_HISTORY_IGNORE="cd *"
# ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git *"
# syntax color definition
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

typeset -A ZSH_HIGHLIGHT_STYLES

# ZSH_HIGHLIGHT_STYLES[command]=fg=white,bold
# ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta,bold'

ZSH_HIGHLIGHT_STYLES[default]=none
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=009
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=009,standout
ZSH_HIGHLIGHT_STYLES[alias]=fg=cyan,bold
ZSH_HIGHLIGHT_STYLES[builtin]=fg=cyan,bold
ZSH_HIGHLIGHT_STYLES[function]=fg=cyan,bold
ZSH_HIGHLIGHT_STYLES[command]=fg=white,bold
ZSH_HIGHLIGHT_STYLES[precommand]=fg=white,underline
ZSH_HIGHLIGHT_STYLES[commandseparator]=none
ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=009
ZSH_HIGHLIGHT_STYLES[path]=fg=214,underline
ZSH_HIGHLIGHT_STYLES[globbing]=fg=063
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=white,underline
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=none
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=none
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=063
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=063
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=009
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=009
ZSH_HIGHLIGHT_STYLES[assign]=none

# https://unix.stackexchange.com/questions/250690/how-to-configure-ctrlw-as-delete-word-in-zsh
# autoload -U select-word-style
# select-word-style bash

# export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'
my-backward-delete-word() {
    local WORDCHARS=${WORDCHARS/\//}
    zle backward-delete-word
}
zle -N my-backward-delete-word
bindkey '^W' my-backward-delete-word
# How to know your keymap:
# Run cat -v in your favorite terminal emulator to observe key codes.
# (NOTE: In some cases, cat -v shows the wrong key codes.
# If the key codes shown by cat -v don't work for you,
# press <C-v><UP> and <C-v><DOWN> at your ZSH command line prompt for correct key codes.)

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# omz uses bindkey -s '\el' 'ls\n' to run ls, which is not suitable for me.
bindkey -r '\el'
bindkey '^[L' down-case-word
bindkey '^[l' down-case-word
bindkey '^[U' up-case-word
bindkey '^[u' up-case-word
source ~/.config/common/init.sh
