. ~/.oh-my-zsh/templates/zshrc.zsh-template

HIST_STAMPS="yyyy-mm-dd"
DISABLE_AUTO_UPDATE="true"
ZSH_THEME="ys"


# Note that zsh-syntax-highlighting must be the last plugin sourced.
plugins=(git history systemd z sudo zsh-autosuggestions zsh-completions
        extract safe-paste colored-man-pages
        zsh-syntax-highlighting
        )

ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# config zsh-users/zsh-autosuggestions
# ZSH_AUTOSUGGEST_STRATEGY=(history completion)
# ZSH_AUTOSUGGEST_HISTORY_IGNORE="cd *"
# ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git *"


# How to know your keymap:
# Run cat -v in your favorite terminal emulator to observe key codes.
# (NOTE: In some cases, cat -v shows the wrong key codes.
# If the key codes shown by cat -v don't work for you,
# press <C-v><UP> and <C-v><DOWN> at your ZSH command line prompt for correct key codes.)


source ~/.custom/alias.sh
source ~/.custom/common.sh
source ~/.custom/proxy.sh
source ~/.custom/pyenv.sh
source ~/.custom/epics.sh